--- 
 
- llm_platform: OpenAI
  gpt-4o:
    token_limit: 4096
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 0
    temperature: 0

  gpt-4-turbo:
    token_limit: 4096
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 0
    temperature: 0

- llm_platform: Meta
  llama3-70b-8192:
    token_limit: 8192
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 70
    temperature: 0

  llama-3.1-70b-versatile:
    token_limit: 131072
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 70
    temperature: 0

- llm_platform: Google
  gemini-1.5-pro-latest:
    token_limit: 8192
    max_output_tokens: 8192
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 70
    temperature: 0.2
    top_p: 0.5
    top_k: 32

  gemini-1.5-pro-exp-0801:
    token_limit: 8192
    max_output_tokens: 8192
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 70
    temperature: 0
    top_p: 0.95
    top_k: 64

  gemini-1.5-pro-exp-0827:
    token_limit: 16384
    max_output_tokens: 16384
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 70
    temperature: 0
    top_p: 0.95
    top_k: 64

  gemini-1.0-pro-001:
    token_limit: 8192
    max_output_tokens: 8192
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 70
    temperature: 0
    top_p: 0.95
    top_k: 64






