CATEGORICAL_RATIO: float = 0.01


class REPRESENTATION_TYPE:
    TEXT = "TEXT"
    #--------------------
    NUMBER_SIGN = "NUMBERSIGN"
    BASELINE = "BASELINE"
    INSTRUCTION = "INSTRUCTION"
    NUMBER_SIGN_WFK = "NUMBERSIGNWFK"
    BASELINE_WOFK = "BASELINEWOFK"
    TEXT_WFK = "TEXTWFK"
    INSTRUCTION_WFK = "INSTRUCTIONWFK"
    NUMBER_SIGN_WORULE = "NUMBERSIGNWORULE"
    SQL_WRULE = "SQLWRULE"
    INSTRUCTION_WRULE = "INSTRUCTIONWRULE"
    TEXT_WRULE = "TEXTWRULE"
    SQL_COT = "SQLCOT"
    TEXT_COT = "TEXTCOT"
    NUMBER_SIGN_COT = "NUMBERSIGNCOT"
    INSTRUCTION_COT = "INSTRUCTIONCOT"
    CBR = "CBR"
